//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class area_list {
    
    private Area[] areaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("area")]
    public Area[] area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class Area {
    
    private ulong idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private ulong direct_member_countField;
    
    private ulong member_weightField;
    
    private ulong autoreject_weightField;
    
    private bool activeField;
    
    /// <remarks/>
    public ulong id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ulong direct_member_count {
        get {
            return this.direct_member_countField;
        }
        set {
            this.direct_member_countField = value;
        }
    }
    
    /// <remarks/>
    public ulong member_weight {
        get {
            return this.member_weightField;
        }
        set {
            this.member_weightField = value;
        }
    }
    
    /// <remarks/>
    public ulong autoreject_weight {
        get {
            return this.autoreject_weightField;
        }
        set {
            this.autoreject_weightField = value;
        }
    }
    
    /// <remarks/>
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
}
