//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class initiative_list {
    
    private Initiative[] initiativeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("initiative")]
    public Initiative[] initiative {
        get {
            return this.initiativeField;
        }
        set {
            this.initiativeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class Initiative {
    
    private ulong area_idField;
    
    private string area_nameField;
    
    private ulong issue_idField;
    
    private string issue_stateField;
    
    private string issue_createdField;
    
    private string issue_acceptedField;
    
    private string issue_half_frozenField;
    
    private string issue_fully_frozenField;
    
    private string issue_closedField;
    
    private string issue_admission_timeField;
    
    private string issue_discussion_timeField;
    
    private string issue_verification_timeField;
    
    private string issue_voting_timeField;
    
    private bool issue_ranks_availableField;
    
    private ulong policy_issue_quorum_numField;
    
    private ulong policy_issue_quorum_denField;
    
    private ulong policy_initiative_quorum_numField;
    
    private ulong policy_initiative_quorum_denField;
    
    private ulong policy_majority_numField;
    
    private ulong policy_majority_denField;
    
    private bool policy_majority_strictField;
    
    private ulong idField;
    
    private string nameField;
    
    private string discussion_urlField;
    
    private string createdField;
    
    private string revokedField;
    
    private string suggested_initiative_idField;
    
    private string admittedField;
    
    private string issue_populationField;
    
    private string supporter_countField;
    
    private string informed_supporter_countField;
    
    private string satisfied_supporter_countField;
    
    private string satisfied_informed_supporter_countField;
    
    private string issue_vote_nowField;
    
    private string issue_vote_laterField;
    
    private string issue_voter_countField;
    
    private string positive_votesField;
    
    private string negative_votesField;
    
    private string agreedField;
    
    private string rankField;
    
    private string current_draft_createdField;
    
    private string current_draft_formatting_engineField;
    
    private string current_draft_contentField;
    
    public Initiative() {
        this.issue_ranks_availableField = false;
    }
    
    /// <remarks/>
    public ulong area_id {
        get {
            return this.area_idField;
        }
        set {
            this.area_idField = value;
        }
    }
    
    /// <remarks/>
    public string area_name {
        get {
            return this.area_nameField;
        }
        set {
            this.area_nameField = value;
        }
    }
    
    /// <remarks/>
    public ulong issue_id {
        get {
            return this.issue_idField;
        }
        set {
            this.issue_idField = value;
        }
    }
    
    /// <remarks/>
    public string issue_state {
        get {
            return this.issue_stateField;
        }
        set {
            this.issue_stateField = value;
        }
    }
    
    /// <remarks/>
    public string issue_created {
        get {
            return this.issue_createdField;
        }
        set {
            this.issue_createdField = value;
        }
    }
    
    /// <remarks/>
    public string issue_accepted {
        get {
            return this.issue_acceptedField;
        }
        set {
            this.issue_acceptedField = value;
        }
    }
    
    /// <remarks/>
    public string issue_half_frozen {
        get {
            return this.issue_half_frozenField;
        }
        set {
            this.issue_half_frozenField = value;
        }
    }
    
    /// <remarks/>
    public string issue_fully_frozen {
        get {
            return this.issue_fully_frozenField;
        }
        set {
            this.issue_fully_frozenField = value;
        }
    }
    
    /// <remarks/>
    public string issue_closed {
        get {
            return this.issue_closedField;
        }
        set {
            this.issue_closedField = value;
        }
    }
    
    /// <remarks/>
    public string issue_admission_time {
        get {
            return this.issue_admission_timeField;
        }
        set {
            this.issue_admission_timeField = value;
        }
    }
    
    /// <remarks/>
    public string issue_discussion_time {
        get {
            return this.issue_discussion_timeField;
        }
        set {
            this.issue_discussion_timeField = value;
        }
    }
    
    /// <remarks/>
    public string issue_verification_time {
        get {
            return this.issue_verification_timeField;
        }
        set {
            this.issue_verification_timeField = value;
        }
    }
    
    /// <remarks/>
    public string issue_voting_time {
        get {
            return this.issue_voting_timeField;
        }
        set {
            this.issue_voting_timeField = value;
        }
    }
    
    /// <remarks/>
    public bool issue_ranks_available {
        get {
            return this.issue_ranks_availableField;
        }
        set {
            this.issue_ranks_availableField = value;
        }
    }
    
    /// <remarks/>
    public ulong policy_issue_quorum_num {
        get {
            return this.policy_issue_quorum_numField;
        }
        set {
            this.policy_issue_quorum_numField = value;
        }
    }
    
    /// <remarks/>
    public ulong policy_issue_quorum_den {
        get {
            return this.policy_issue_quorum_denField;
        }
        set {
            this.policy_issue_quorum_denField = value;
        }
    }
    
    /// <remarks/>
    public ulong policy_initiative_quorum_num {
        get {
            return this.policy_initiative_quorum_numField;
        }
        set {
            this.policy_initiative_quorum_numField = value;
        }
    }
    
    /// <remarks/>
    public ulong policy_initiative_quorum_den {
        get {
            return this.policy_initiative_quorum_denField;
        }
        set {
            this.policy_initiative_quorum_denField = value;
        }
    }
    
    /// <remarks/>
    public ulong policy_majority_num {
        get {
            return this.policy_majority_numField;
        }
        set {
            this.policy_majority_numField = value;
        }
    }
    
    /// <remarks/>
    public ulong policy_majority_den {
        get {
            return this.policy_majority_denField;
        }
        set {
            this.policy_majority_denField = value;
        }
    }
    
    /// <remarks/>
    public bool policy_majority_strict {
        get {
            return this.policy_majority_strictField;
        }
        set {
            this.policy_majority_strictField = value;
        }
    }
    
    /// <remarks/>
    public ulong id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string discussion_url {
        get {
            return this.discussion_urlField;
        }
        set {
            this.discussion_urlField = value;
        }
    }
    
    /// <remarks/>
    public string created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    public string revoked {
        get {
            return this.revokedField;
        }
        set {
            this.revokedField = value;
        }
    }
    
    /// <remarks/>
    public string suggested_initiative_id {
        get {
            return this.suggested_initiative_idField;
        }
        set {
            this.suggested_initiative_idField = value;
        }
    }
    
    /// <remarks/>
    public string admitted {
        get {
            return this.admittedField;
        }
        set {
            this.admittedField = value;
        }
    }
    
    /// <remarks/>
    public string issue_population {
        get {
            return this.issue_populationField;
        }
        set {
            this.issue_populationField = value;
        }
    }
    
    /// <remarks/>
    public string supporter_count {
        get {
            return this.supporter_countField;
        }
        set {
            this.supporter_countField = value;
        }
    }
    
    /// <remarks/>
    public string informed_supporter_count {
        get {
            return this.informed_supporter_countField;
        }
        set {
            this.informed_supporter_countField = value;
        }
    }
    
    /// <remarks/>
    public string satisfied_supporter_count {
        get {
            return this.satisfied_supporter_countField;
        }
        set {
            this.satisfied_supporter_countField = value;
        }
    }
    
    /// <remarks/>
    public string satisfied_informed_supporter_count {
        get {
            return this.satisfied_informed_supporter_countField;
        }
        set {
            this.satisfied_informed_supporter_countField = value;
        }
    }
    
    /// <remarks/>
    public string issue_vote_now {
        get {
            return this.issue_vote_nowField;
        }
        set {
            this.issue_vote_nowField = value;
        }
    }
    
    /// <remarks/>
    public string issue_vote_later {
        get {
            return this.issue_vote_laterField;
        }
        set {
            this.issue_vote_laterField = value;
        }
    }
    
    /// <remarks/>
    public string issue_voter_count {
        get {
            return this.issue_voter_countField;
        }
        set {
            this.issue_voter_countField = value;
        }
    }
    
    /// <remarks/>
    public string positive_votes {
        get {
            return this.positive_votesField;
        }
        set {
            this.positive_votesField = value;
        }
    }
    
    /// <remarks/>
    public string negative_votes {
        get {
            return this.negative_votesField;
        }
        set {
            this.negative_votesField = value;
        }
    }
    
    /// <remarks/>
    public string agreed {
        get {
            return this.agreedField;
        }
        set {
            this.agreedField = value;
        }
    }
    
    /// <remarks/>
    public string rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    public string current_draft_created {
        get {
            return this.current_draft_createdField;
        }
        set {
            this.current_draft_createdField = value;
        }
    }
    
    /// <remarks/>
    public string current_draft_formatting_engine {
        get {
            return this.current_draft_formatting_engineField;
        }
        set {
            this.current_draft_formatting_engineField = value;
        }
    }
    
    /// <remarks/>
    public string current_draft_content {
        get {
            return this.current_draft_contentField;
        }
        set {
            this.current_draft_contentField = value;
        }
    }
}
